name: Deploy to docker

on:
  push:
    branches:
      - main

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build . --tag gocaptcha:latest

      - name: Publish Docker image
        uses: elgohr/Publish-Docker-Github-action@master
        with:
          name: polylmao/gocaptcha
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
