name: Deploy to docker

on:
  push:
    branches:
      - main

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: docker build . -t gocaptcha
      - name: Tag Docker image
        run: docker tag gocaptcha:latest polylmao/gocaptcha:latest
      - name: Push Docker image
